apiVersion: v1
kind: Pod
metadata:
  name: objstor-backup
spec:
  restartPolicy: Never
  containers:
  - name: objstor-backup
    image: objstor-backup:0.1
    volumeMounts:
    - name: config-volume
      mountPath: /etc/objstor-backup

  volumes:
  - name: config-volume
    configMap:
      name: objstor-backup-config
